# Generated by Django 3.0.4 on 2020-04-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='total',
            field=models.CharField(default='123', max_length=21),
        ),
    ]
